name: release

on:
  push:
    branches:
    - main
    paths:
    - meetings/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"

          for added_file in "${added_files[@]}"; do
            if [[ ${added_file} == meetings/* ]]
            then
              tag=$(echo "${added_file}" | grep -oP '(?<=meetings/)[^\./]+')
              echo "tag=${tag}" >> "$GITHUB_ENV"  # set GH env var so other action can access it
              echo tag set to "${tag}"
              break
            fi
          done
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --depth=1 --tags
      # - name: exit fast if tag exists
      - run: |
          if [[ ! $(git tag -l "${{env.tag}}") ]]; then
            gh release create "${{env.tag}}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
