name: release

on:
  push:
    branches:
    - main
    paths:
    - meetings/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"

          for added_file in "${added_files[@]}"; do
            if [[ ${added_file} == meetings/* ]]
            then
              tag=$(echo "${added_file}" | grep -oP '(?<=meetings/)[^\./]+')
              echo "tag=${tag}" >> "$GITHUB_ENV"  # set GH env var so other action can access it
              echo tag set to "${tag}"
              break
            fi
          done
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --depth=1 --tags
      # - name: exit fast if tag exists
      - run: |
          if [[ $(git tag -l "${{env.tag}}") ]]; then
            echo tag/release exists, exiting
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{env.tag}}
          tag_prefix:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.tag}}
